- name: (v2.2) Search-only, return list of updates found (if any), log to c:\ansible_wu.txt
  hosts: all
  tasks:
    - name: (v2.2) Search-only, return list of updates found (if any), log to c:\ansible_wu.txt
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
        state: searched
        log_path: "C:\nsible.txt"
