- name: Install updates and reboot
  hosts: all
  tasks:
    - name: Install updates and reboot
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
        log_path: "C:\ansible\ansible.txt"
        reboot: yes
